"""由 tools/gen_mission_titles.py 从 main.scm + american.gxt 提取，请勿手改。

每条对应关系都有实据：任务标题的 GXT key 出现在该任务脚本的字节码区段内。
重新生成：python tools/gen_mission_titles.py
"""

# 脚本代号（小写）→ 游戏内任务标题（英文原文）
SCRIPT_TITLES: dict[str, str] = {
    "bcesar": "Wu Zi Mu",
    "bcesar4": "Wu Zi Mu",
    "bcrash": "Badlands",
    "bcrash1": "Badlands",
    "blood": "Blood Ring",
    "casin10": "Saint Mark's Bistro",
    "casino1": "Fender Ketchup",
    "casino3": "You've had your Chips",
    "casino4": "Don Peyote",
    "casino5": "Intensive Care",
    "casino6": "The Meat Business",
    "casino7": "Fish in a Barrel",
    "casino9": "Freefall",
    "cat1": "Local Liquor Store",
    "cat2": "Small Town Bank",
    "cat3": "Tanker Commander",
    "cat4": "Against All Odds",
    "crash1": "Burning Desire",
    "crash4": "Doberman",
    "des3": "Interdiction",
    "desert4": "Verdant Meadows",
    "desert5": "Learning to Fly",
    "desert9": "Stowaway",
    "doc": "Madd Dogg",
    "doc2": "Madd Dogg",
    "driv2": "T-Bone Mendez",
    "driv3": "Mike Toreno",
    "driv6": "Lure",
    "drugs1": "Just Business",
    "drugs3": "Gray Imports",
    "drugs4": "Reuniting the Families",
    "dskool": "Back to School",
    "farlie4": "Ran Fa Li",
    "finalec": "End Of The Line",
    "garag1": "Wear Flowers in your Hair",
    "grove1": "Beat Down on B Dup",
    "grove2": "Grove 4 Life",
    "guns1": "Home Invasion",
    "heist1": "Architectural Espionage",
    "heist2": "Dam and Blast",
    "heist3": "Key to her Heart",
    "heist4": "Cop Wheels",
    "heist9": "Breaking the Bank at Caligula's",
    "hoods5": "Sweet's Girl",
    "maf4": "Black Project",
    "mansio1": "A Home In The Hills",
    "mansio2": "Vertical Bird",
    "mansio3": "Home Coming",
    "manson5": "Cut Throat Business",
    "music1": "Life's a Beach",
    "music2": "Madd Dogg's Rhymes",
    "music3": "Management Issues",
    "music5": "House Party",
    "otb": "Inside Track Betting",
    "psch": "Learning to Fly",
    "quarry": "Quarry",
    "quarrys": "Quarry",
    "riot1": "Riot",
    "riot2": "Los Desperados",
    "ryder2": "Robbing Uncle Sam",
    "ryder3": "Catalyst",
    "scrash": "Snail Trail",
    "scrash2": "Snail Trail",
    "smoke2": "Running Dog",
    "smoke3": "Wrong Side of the Tracks",
    "steal1": "Zeroing In",
    "steal2": "Test Drive",
    "steal4": "Customs Fast Track",
    "steal5": "Puncture Wounds",
    "sweet1": "Tagging up Turf",
    "sweet1b": "Cleaning the Hood",
    "sweet2": "Nines and AK's",
    "sweet3": "Drive-thru",
    "sweet4": "Drive-By",
    "sweet6": "Cesar Vialpando",
    "sweet7": "Los Sepulcros",
    "syn1": "Photo Opportunity",
    "syn2": "Jizzy",
    "syn3": "Outrider",
    "syn5": "Pier 69",
    "syn6": "Toreno's Last Flight",
    "syn7": "Yay Ka-Boom-Boom",
    "synd4": "Ice Cold Killa",
    "toreno1": "Monster",
    "toreno2": "Highjack",
    "tru": "Body Harvest",
    "truck": "Trucking",
    "trucks": "Trucking",
    "truth1": "Body Harvest",
    "twar7": "OG Loc",
    "vcrash": "Misappropriation",
    "vcrash1": "Misappropriation",
    "wuzi1": "Mountain Cloud Boys",
    "wuzi2": "Amphibious Assault",
    "wuzi5": "The Da Nang Thang",
    "zero1": "Air Raid",
    "zero4": "New Model Army",
}
